replicaCount: 1

image:
  repository: adithyabathineni/whiteboard
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

resources: {}
serviceAccount:
  create: true
  name: ""
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
